// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpBtBq9egwU4wgPktIYA12Lpgr7NEsIo',
    appId: '1:1022483005700:web:fc246b48701f9a8f9e9051',
    messagingSenderId: '1022483005700',
    projectId: 'coffeelp',
    authDomain: 'coffeelp.firebaseapp.com',
    storageBucket: 'coffeelp.appspot.com',
    measurementId: 'G-WZSCVMJH52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbDRwBHzgKmN7X5m0-btmsT_la6Fvd-aQ',
    appId: '1:1022483005700:android:823a24a5d15966659e9051',
    messagingSenderId: '1022483005700',
    projectId: 'coffeelp',
    storageBucket: 'coffeelp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmn1SAsS56ScYe29YQa1V4eMf2JZUb44',
    appId: '1:1022483005700:ios:e559aea7499264d29e9051',
    messagingSenderId: '1022483005700',
    projectId: 'coffeelp',
    storageBucket: 'coffeelp.appspot.com',
    iosBundleId: 'com.example.lp2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmn1SAsS56ScYe29YQa1V4eMf2JZUb44',
    appId: '1:1022483005700:ios:e559aea7499264d29e9051',
    messagingSenderId: '1022483005700',
    projectId: 'coffeelp',
    storageBucket: 'coffeelp.appspot.com',
    iosBundleId: 'com.example.lp2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkpBtBq9egwU4wgPktIYA12Lpgr7NEsIo',
    appId: '1:1022483005700:web:ef5d7e7ec48be46c9e9051',
    messagingSenderId: '1022483005700',
    projectId: 'coffeelp',
    authDomain: 'coffeelp.firebaseapp.com',
    storageBucket: 'coffeelp.appspot.com',
    measurementId: 'G-BECEH8EPP0',
  );

}